name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit
  deploy:
    name: "Deploy to VPS"
    needs: test
    runs-on: ubuntu-latest
    continue-on-error: true
    if: always()
    steps:
      - name: Send a Discord Notification on Test Failure
        if: needs.test.result == 'failure'
        run: >
            curl -H "Content-Type: application/json" -X POST -d '{"content": "🚨 Deployment Failed due to error(s) in tests", "username": "Sylvester Stallone", "avatar_url": "https://i.imgur.com/aXsoEHR.jpeg"}' "${{ secrets.DISCORD_WEBHOOK }}"

      - name: Configure SSH
        if: success() && needs.test.result == 'success'
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy-key.pem
          chmod 600 ~/.ssh/deploy-key.pem
          cat >> ~/.ssh/config <<END
          Host my-vps
            HostName $SSH_IP
            User $SSH_USER
            IdentityFile ~/.ssh/deploy-key.pem
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_IP: ${{ secrets.SSH_IP }}

      - name: Deploy site
        if: success() && needs.test.result == 'success'
        run: ssh my-vps 'cd ${{ secrets.PROJECT_ROOT }}/src/scripts && chmod +x redeploy-site.sh && ./redeploy-site.sh'

      - name: Send a Discord Notification on Deployment Failure
        if: failure() && needs.test.result == 'success'
        run: >
            curl -H "Content-Type: application/json" -X POST -d '{"content": "🚨 Deployment Failed due to a problem in either ssh or redeploy-site.sh", "username": "Sylvester Stallone", "avatar_url": "https://i.imgur.com/aXsoEHR.jpeg"}' "${{ secrets.DISCORD_WEBHOOK }}"

      - name: Send a Discord Notification on Deployment Success
        if: success() && needs.test.result == 'success'
        run: >
          curl -H "Content-Type: application/json" -X POST -d '{"content": "🚀 Deployment Successful", "username": "Arnold Schwarzenegger", "avatar_url": "https://i.imgur.com/fCFMcZf.jpeg"}' "${{ secrets.DISCORD_WEBHOOK }}"